"""add unique constraint to user_limits.user_id

Revision ID: 49ae216ef796
Revises: 591896e1d365
Create Date: 2026-07-03 11:43:10.872905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49ae216ef796'
down_revision: Union[str, Sequence[str], None] = '591896e1d365'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user_limits', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_limits', type_='unique')
    # ### end Alembic commands ###
